[functions.calculate-shipping]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.notify-booking]
verify_jwt = false

[functions.notify-contact]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
